#!/bin/sh

export FC="gfortran -w -O3"
export CC="gcc"
export DSTRIP="./dstrip"

# build the dstrip utility
$CC -o dstrip dstrip.c

FILE="adaptri"

DFILES="print            \
"

LFILES=""

for file in ${DFILES}
do
LFILES="${LFILES} ${file}.o"
done

# compile the code from which debugging headers are to be stripped.
./FCOMP $DFILES


# link 'em
echo linking ...
${FC} -o int2 ${FILE}.f ${LFILES}  
rm -f ${FILE}.o

read -p "hit enter to run ..." var
echo ""
echo ""
echo ""

./int2
